apiVersion: apps/v1
kind: Deployment
metadata:
  name: solra-backend
spec:
  template:
    spec:
      containers:
        - name: solra-backend
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          envFrom:
            - configMapRef:
                name: solra-config
            - secretRef:
                name: prod-secret
