apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solra
resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
  - name: ghcr.io/fisa4th-final-project/solra-backend
    newTag: f29bcac3e9b5155debb5390795e44d09da748790

