apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solra
resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
  - name: ghcr.io/fisa4th-final-project/solra-backend
    newTag: cf4e083b50b6020a33cbaed109cc4c9f20d5d9e6

