apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solra
resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
  - name: dyoun12/solra-backend
    newTag: 83446e57ce65544e89d9fbf60d9366e29cdb89f0
