apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solra
resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
  - name: ghcr.io/fisa4th-final-project/solra-backend
    newTag: 9b461902eff2e338d3bc04a2bc3d12e80b4f7568

