apiVersion: apps/v1
kind: Deployment
metadata:
  name: solra-backend
  namespace: solra
spec:
  template:
    spec:
      containers:
        - name: solra-backend
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          envFrom:
            - configMapRef:
                name: solra-config
            - secretRef:
                name: dev-secret
