apiVersion: apps/v1
kind: Deployment
metadata:
  name: solra-backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: solra-backend
  template:
    metadata:
      labels:
        app: solra-backend
    spec:
      containers:
        - name: solra-backend
          image: ghcr.io/fisa4th-final-project/solra-backend