# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: solra-secret
    envs:
      - /home/ubuntu/env/solra-secret.env
    type: Opaque