apiVersion: v1
kind: Service
metadata:
  name: solra-backend
  namespace: solra
spec:
  type: NodePort
  selector:
    app: solra-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
