name: CI/CD for solra-backend

on:
  push:
    branches: [dev, main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Spring Boot App to Jar
        run: |
          chmod +x ./app/gradlew
          cd app
          ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Update kustomization.yaml image tag
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [ "$BRANCH" = "dev" ]; then
            OVERLAY_PATH=deploy/overlays/dev/kustomization.yaml
          elif [ "$BRANCH" = "main" ]; then
            OVERLAY_PATH=deploy/overlays/prod/kustomization.yaml
          else
            echo "No overlay for branch $BRANCH"; exit 0
          fi

          sed -i "s|newTag:.*|newTag: ${{ github.sha }}|" "$OVERLAY_PATH"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "$OVERLAY_PATH"
          git commit -m "deploy: imageTag > $BRANCH: ${{ github.sha }}"
          git push
